n = input('say anything mf ')
print('is a number?', n.isnumeric())
print('is alpha?', n.isalpha())
print('is alnum?', n.isalnum())
print('is in upper?', n.isupper())
print('is space?', n.isspace())
print(type(n))
